include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - unnecessary_this
    - avoid_unnecessary_containers
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - prefer_single_quotes
    - always_declare_return_types
    - avoid_empty_else
    - avoid_returning_null_for_void
    - cancel_subscriptions
    - close_sinks
    - valid_regexps

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
